import { Minus, Plus, ShoppingBag, Trash2, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { formatPrice } from '../lib/data'
import { useStore } from '../store/useStore'

export default function CartDrawer() {
  const { cart, isCartOpen, setCartOpen, updateQuantity, removeFromCart } = useStore(); const total = cart.reduce((sum, i) => sum + i.price * i.quantity, 0)
  return <><div onClick={() => setCartOpen(false)} className={`fixed inset-0 z-50 bg-slate-950/30 transition ${isCartOpen ? 'visible opacity-100' : 'invisible opacity-0'}`}/><aside className={`fixed right-0 top-0 z-50 flex h-dvh w-full max-w-md flex-col bg-white shadow-2xl transition-transform ${isCartOpen ? 'translate-x-0' : 'translate-x-full'}`} aria-label="Shopping cart"><header className="flex items-center justify-between border-b p-5"><div className="flex items-center gap-2"><ShoppingBag className="text-emerald-600"/><h2 className="text-lg font-bold">Your cart</h2></div><button onClick={() => setCartOpen(false)} aria-label="Close cart" className="p-2"><X/></button></header><div className="flex-1 overflow-y-auto p-5">{cart.length === 0 ? <div className="grid h-full place-items-center text-center"><div><span className="text-5xl">🛒</span><p className="mt-4 font-semibold">Your cart is empty</p><p className="mt-1 text-sm text-slate-500">Find everything you need.</p><button onClick={() => setCartOpen(false)} className="mt-5 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Browse products</button></div></div> : <div className="space-y-4">{cart.map((i) => <div key={i.id} className="flex gap-3"><div className="grid h-16 w-16 place-items-center rounded-xl bg-stone-100 text-3xl">{i.emoji}</div><div className="min-w-0 flex-1"><div className="flex justify-between"><div><p className="truncate font-semibold">{i.name}</p><p className="text-xs text-slate-500">{i.unit}</p></div><button onClick={() => removeFromCart(i.id)} aria-label={`Remove ${i.name}`}><Trash2 size={17}/></button></div><div className="mt-2 flex items-center justify-between"><div className="rounded-lg border"><button onClick={() => updateQuantity(i.id,i.quantity-1)} className="p-1.5"><Minus size={14}/></button><span className="px-2 text-sm font-semibold">{i.quantity}</span><button onClick={() => updateQuantity(i.id,i.quantity+1)} className="p-1.5"><Plus size={14}/></button></div><p className="font-semibold">{formatPrice(i.price*i.quantity)}</p></div></div></div>)}</div>}</div>{cart.length > 0 && <footer className="border-t p-5"><p className="mb-1 text-center text-xs text-emerald-700">{total >= 70000 ? 'You qualify for free shipping' : `${formatPrice(70000-total)} away from free shipping`}</p><div className="mb-4 h-2 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-emerald-500" style={{width:`${Math.min(100,total/700)}%`}}/></div><div className="mb-4 flex justify-between font-bold"><span>Total</span><span>{formatPrice(total)}</span></div><Link to="/cart" onClick={() => setCartOpen(false)} className="block rounded-xl bg-emerald-600 py-3 text-center font-semibold text-white">View cart and checkout</Link></footer>}</aside></>
}
