import { Bot, Send, Sparkles, X } from 'lucide-react'
import { useState } from 'react'
import { api } from '../lib/api'
import { useStore } from '../store/useStore'

export default function ShoppingAssistant() {
  const [open, setOpen] = useState(false); const [input, setInput] = useState('');
  const [messages, setMessages] = useState([{ role: 'bot', text: '¡Hola! Puedo armar tu receta y añadir sus ingredientes al carrito.' }]);
  const [loading, setLoading] = useState(false); const addManyToCart = useStore((state) => state.addManyToCart); const cart = useStore((state) => state.cart);
  const send = async (event) => { event.preventDefault(); const text = input.trim(); if (!text || loading) return; setMessages((current) => [...current, { role: 'user', text }]); setInput(''); setLoading(true); try { const answer = await api('/api/agent/chat', { method: 'POST', body: JSON.stringify({ message: text }) }); const selected = answer.recommendations || []; if (selected.length) addManyToCart(selected); const summary = answer.summary; const money = (value) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: summary.currency }).format(value); const cartSubtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0) + (summary?.subtotal || 0); const cartShipping = cartSubtotal >= 70000 ? 0 : 7900; const feedback = summary?.withinBudget === false ? `\n\nPresupuesto máximo: ${money(summary.budget)}. Total de la receta con envío: ${money(summary.total)}. No se modificó tu carrito.` : summary ? `\n\nSelección completa añadida al carrito (${summary.items.length} productos).\nMotivo: ${summary.reason}.\nSubtotal de esta selección: ${money(summary.subtotal)}. Envío: ${summary.shipping ? money(summary.shipping) : 'Gratis'}.\nTotal actual estimado del carrito: ${money(cartSubtotal + cartShipping)}.\nProductos: ${summary.items.map((product) => `${product.name} ⭐${product.rating}`).join(', ')}.` : ''; setMessages((current) => [...current, { role: 'bot', text: `${answer.response}${feedback}` }]); } catch (error) { setMessages((current) => [...current, { role: 'bot', text: error.message }]); } finally { setLoading(false); } };
  return <div className="fixed bottom-5 right-5 z-30"><button onClick={() => setOpen(!open)} aria-label="Abrir asistente de compras" className="ml-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-600 text-white shadow-lg shadow-emerald-700/30 transition hover:scale-105">{open ? <X/> : <Bot/>}</button>{open && <section className="absolute bottom-16 right-0 flex h-[440px] w-[min(360px,calc(100vw-2.5rem))] flex-col overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-2xl"><header className="flex items-center gap-3 bg-slate-900 p-4 text-white"><div className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-500"><Sparkles size={18}/></div><div><h2 className="font-bold">Asistente markECIA</h2><p className="text-xs text-slate-300">Recetas y carrito inteligente</p></div></header><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map((message, index) => <div key={index} className={`whitespace-pre-line rounded-2xl px-3 py-2.5 text-sm leading-5 ${message.role === 'user' ? 'ml-8 bg-emerald-600 text-white' : 'mr-5 bg-stone-100 text-slate-700'}`}><p>{message.text}</p></div>)}{loading && <p className="text-xs text-slate-500">Buscando y añadiendo productos…</p>}</div><form onSubmit={send} className="flex gap-2 border-t border-stone-100 p-3"><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ej. Arroz con pollo para 4" className="min-w-0 flex-1 rounded-xl bg-stone-100 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-emerald-500"/><button disabled={loading} className="rounded-xl bg-emerald-600 p-2 text-white disabled:opacity-50"><Send size={18}/></button></form></section>}</div>
}
