import { Bot, Send, Sparkles, X } from 'lucide-react'
import { useState } from 'react'
import { api } from '../lib/api'
import { useStore } from '../store/useStore'

export default function ShoppingAssistant() {
  const [open, setOpen] = useState(false); const [input, setInput] = useState(''); const [messages, setMessages] = useState([{ role: 'bot', text: 'Hi! I can build your recipe and add its ingredients to your cart.' }]); const [loading, setLoading] = useState(false)
  const addMissingToCart = useStore((s) => s.addMissingToCart); const cart = useStore((s) => s.cart)
  const send = async (event) => { event.preventDefault(); const text = input.trim(); if (!text || loading) return; setMessages((m) => [...m, { role: 'user', text }]); setInput(''); setLoading(true); try { const answer = await api('/api/agent/chat', { method: 'POST', body: JSON.stringify({ message: text }) }); const selected = answer.recommendations || []; const existing = new Set(cart.map((i) => i.id)); const added = selected.filter((p) => !existing.has(p.id)); if (added.length) addMissingToCart(added); const s = answer.summary; const money = (value) => new Intl.NumberFormat('en-US', { style: 'currency', currency: s?.currency || 'COP' }).format(value); const current = cart.reduce((sum, i) => sum + i.price * i.quantity, 0); const addedTotal = added.reduce((sum, i) => sum + i.price, 0); const cartTotal = current + addedTotal; const shipping = cartTotal >= 70000 ? 0 : 7900; const feedback = s?.withinBudget === false ? `\n\nMaximum budget: ${money(s.budget)}. Recipe total with shipping: ${money(s.total)}. Your cart was not changed.` : s ? `\n\n${added.length ? `I added ${added.length} new product${added.length === 1 ? '' : 's'} to your cart.` : 'These ingredients are already in your cart, so I did not increase their quantities.'}\nReason: ${s.reason}.\nSelection subtotal: ${money(s.subtotal)}. Selection shipping: ${s.shipping ? money(s.shipping) : 'Free'}.\nCurrent estimated cart total: ${money(cartTotal + shipping)}.` : ''; setMessages((m) => [...m, { role: 'bot', text: `${answer.response}${feedback}` }]) } catch (error) { setMessages((m) => [...m, { role: 'bot', text: error.message }]) } finally { setLoading(false) } }
  return <div className="fixed bottom-5 right-5 z-30"><button onClick={() => setOpen(!open)} aria-label="Open shopping assistant" className="ml-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-600 text-white shadow-lg">{open ? <X/> : <Bot/>}</button>{open && <section className="absolute bottom-16 right-0 flex h-[440px] w-[min(360px,calc(100vw-2.5rem))] flex-col overflow-hidden rounded-2xl border bg-white shadow-2xl"><header className="flex items-center gap-3 bg-slate-900 p-4 text-white"><div className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-500"><Sparkles size={18}/></div><div><h2 className="font-bold">MarkECIA assistant</h2><p className="text-xs text-slate-300">Recipes and smart cart</p></div></header><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map((m, i) => <div key={i} className={`whitespace-pre-line rounded-2xl px-3 py-2.5 text-sm leading-5 ${m.role === 'user' ? 'ml-8 bg-emerald-600 text-white' : 'mr-5 bg-stone-100 text-slate-700'}`}><p>{m.text}</p></div>)}{loading && <p className="text-xs text-slate-500">Finding and adding products…</p>}</div><form onSubmit={send} className="flex gap-2 border-t p-3"><input value={input} onChange={(e) => setInput(e.target.value)} placeholder="E.g. chicken and rice for 4" className="min-w-0 flex-1 rounded-xl bg-stone-100 px-3 py-2 text-sm outline-none"/><button disabled={loading} className="rounded-xl bg-emerald-600 p-2 text-white disabled:opacity-50"><Send size={18}/></button></form></section>}</div>
}
